# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e12698e1108043b6ea4640e7da5817f4478586580c10b4dba25029e76841ac3c66685b06aad99472fbcbbe1031838339323dd81b69fa6b338b28518dfb5b483c

test:
  secret_key_base: 13c10e83a712d576aafd92c0fde1d960ce5d4dae7e13c0f1efed1490d8b7fe732ec6b0941a0f79ce3aaac4280ddad3eaca897efb228eb9992f22462759e78c52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
